#!/usr/bin/env python
"""Generate Init_Pos_X_Lo / Init_Pos_Y tables for 37Balls from an ASCII grid.

The startup image is spelled out by the balls themselves, two digits side by
side.  Each digit is a 6-column x 6-row cell grid; a '#' places a ball, any
other character leaves the cell empty.

Balls are 32px but the cell steps are 18 (X) and 13 (Y), so neighbours overlap
heavily - that overlap is what makes the strokes read as solid rather than as a
row of separate circles.

    X, left digit  (col 0-5)  = (col + 1) * 18   ->  $12 .. $6C
    X, right digit (col 6-11) = (col + 3) * 18   ->  $A2 .. $FC
    Y              (row r)    = y_origin + r * 13

The two-column gap between the digits is why the right digit is offset by 3
rather than 1.

The grid may have any number of rows - y_origin is derived so the image is
CENTRED vertically, rather than hard against the top of the screen as the
original 37-ball layout was.  Nine rows is the sweet spot: it is the only row
count whose centred origin lands on a whole pixel, giving identical 52px
margins top and bottom, and 6x9 is a natural proportion for a digit.

Balls are emitted ROW-MAJOR (all of row 0, then row 1, ...).  This matters:
NTSC draws only the first MAX_SPRITES_NTSC balls, so row-major degrades to the
top of the image instead of something scattered.

Usage:
    python tools/gen_layout.py Assets/layout48.txt --count 48
"""

import argparse
import sys

X_STEP = 18
Y_STEP = 13
COLS = 12
DIGIT_COLS = 6
BALL = 32
SCREEN_H = 240
X_CLAMP = 288           # Set_Positions clamps X here
Y_CLAMP = 200           # ...and Y at Y_POS_MAX, derived from CLEAR_H


def x_for(col):
    """Cell column -> X pixel.  The right digit sits two columns further on."""
    return (col + 1) * X_STEP if col < DIGIT_COLS else (col + 3) * X_STEP


def y_origin(rows):
    """Top row's Y, chosen so the whole image is vertically centred."""
    return (SCREEN_H - ((rows - 1) * Y_STEP + BALL)) // 2


def y_for(row, rows):
    return y_origin(rows) + row * Y_STEP


def read_grid(path):
    """Parse the grid, ignoring blank lines and '; ...' comment lines."""
    rows = []
    for raw in open(path, encoding="latin-1"):
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith(";"):
            continue
        cells = [c == "#" for c in line[:COLS].ljust(COLS)]
        rows.append(cells)
    if not rows:
        sys.exit("error: no grid rows found in %s" % path)
    return rows


def emit(name, values, comment):
    out = ["%s" % name]
    for i in range(0, len(values), 16):
        chunk = values[i:i + 16]
        out.append("\tdta " + ",".join("$%02X" % v for v in chunk) +
                   "\t; Objs $%02X-$%02X" % (i, i + len(chunk) - 1))
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("grid")
    ap.add_argument("--count", type=int, required=True,
                    help="expected ball count (must equal MAX_SPRITES_PAL)")
    args = ap.parse_args()

    rows = read_grid(args.grid)
    nrows = len(rows)
    xs, ys = [], []
    for r in range(nrows):
        for c in range(COLS):
            if rows[r][c]:
                xs.append(x_for(c))
                ys.append(y_for(r, nrows))

    # The whole point of this tool: a grid with the wrong number of '#' would
    # otherwise show up as a silent visual bug (missing balls, or balls left at
    # whatever the previous table held).
    if len(xs) != args.count:
        sys.exit("error: grid has %d balls, expected %d (edit %s)"
                 % (len(xs), args.count, args.grid))

    for v, what, limit in ((max(xs), "X", X_CLAMP), (max(ys), "Y", Y_CLAMP)):
        if v > limit:
            sys.exit("error: max %s is %d, past the %d clamp" % (what, v, limit))

    print("; %d balls in a %dx%d grid, generated by tools/gen_layout.py from %s"
          % (len(xs), COLS, nrows, args.grid))
    print("; Y origin %d - image is %d px tall, centred with %d px above and below"
          % (y_origin(nrows), (nrows - 1) * Y_STEP + BALL, y_origin(nrows)))
    print(emit("Init_Pos_X_Lo", xs, None))
    print(emit("Init_Pos_Y", ys, None))


if __name__ == "__main__":
    main()
